/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package transjakarta_;

import java.awt.Color;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import java.util.Arrays;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;

/**
 *
 * @author Home
 */
public class searchRoutesView extends javax.swing.JFrame {

    /**
     * Creates new form searchRoutesView
     */

    String language, from, color;
    Connection con;
    Statement stmt;
    ResultSet rs;
    
    public searchRoutesView() {
        initComponents();
        displayMe();
        this.setLocationRelativeTo(null);
        fromBox.setModel(new DefaultComboBoxModel(getHalte()));
        toBox.setModel(new DefaultComboBoxModel(getHalte()));
    }
    
    public String[] getHalte()
    {
        ArrayList<String> allHalte = new ArrayList();
        String halte;
        String[] sHalte = null;
        try{
            rs = stmt.executeQuery("select * from tj order by halte");
            while(rs.next()){ 
                allHalte.add(rs.getString("halte"));
            }
            for (int i = 0; i<allHalte.size(); i++)
            {
                if(allHalte.get(i).equals(allHalte.get(i++)))
                {
                    allHalte.remove(i); 
                    i--;
                }
            }
        }catch(SQLException e)
        {
           System.out.println(e);
        }
        String[] halteArr = new String[allHalte.size()];System.out.println(allHalte);
        halteArr = allHalte.toArray(halteArr);
        
        return halteArr;
    }
    
    public searchRoutesView(String language, String color, String from) {
        this.from = from;
        this.color = color;
        this.language = language;            
        initComponents();
        displayMe();
        this.setLocationRelativeTo(null);
        connectDB();
        Color();
        fromBox.setModel(new DefaultComboBoxModel(getHalte()));
        toBox.setModel(new DefaultComboBoxModel(getHalte()));
        fromBox.setSelectedItem(from);
    }
    
    public searchRoutesView(String language, String color) {
        this.language = language;
        this.color = color;
        initComponents();
        displayMe();
        this.setLocationRelativeTo(null);
        connectDB();
        Color();
        fromBox.setModel(new DefaultComboBoxModel(getHalte()));
        toBox.setModel(new DefaultComboBoxModel(getHalte()));
    }
    public void displayMe(){
         if ("indo".equals(language)){
            From_label.setText("Dari");
            to.setText("Ke");
            searchroute.setText("CARI RUTE");
            searchRoutesButt.setText("Cari");
            findBSLabel.setText("Cari Halte?");
        }
         else if("english".equals(language)){
            From_label.setText("From");
            to.setText("To");
            searchroute.setText("SEARCH ROUTES");
            searchRoutesButt.setText("Search");
            findBSLabel.setText("Find bus stop?");
         }
    }

    public final void connectDB(){
        try{
            //singleton
            con = ConnectionConfig.createConnection();
            
            stmt = con.createStatement(ResultSet.TYPE_SCROLL_INSENSITIVE, ResultSet.CONCUR_UPDATABLE);
            String query = "SELECT * FROM tj order by halte";
            rs = stmt.executeQuery(query);
            rs.next();
        }catch(SQLException e){
            System.out.println(e);
            //JOptionPane.showMessageDialog(this, e.getMessage());
        }catch (ClassNotFoundException ex) {
            //JOptionPane.showMessageDialog(this, ex.getMessage());
            //Logger.getLogger(JListFirstAssignment.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    public void Color(){
        switch (color) {
            case "pink":
                this.getContentPane().setBackground( Color.PINK );
                break;
            case "gray":
                this.getContentPane().setBackground( Color.LIGHT_GRAY );
                break;
            case "default":
                this.getContentPane().setBackground(null);
                break;
            default:
                this.getContentPane().setBackground(null);
                break;
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        From_label = new javax.swing.JLabel();
        to = new javax.swing.JLabel();
        searchroute = new javax.swing.JLabel();
        searchRoutesButt = new javax.swing.JButton();
        findBSLabel = new javax.swing.JLabel();
        fromBox = new javax.swing.JComboBox<>();
        toBox = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        From_label.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        From_label.setText("From");

        to.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        to.setText("To");

        searchroute.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        searchroute.setText("SEARCH ROUTES");

        searchRoutesButt.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        searchRoutesButt.setText("Search");
        searchRoutesButt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchRoutesButtActionPerformed(evt);
            }
        });

        findBSLabel.setFont(new java.awt.Font("Lucida Grande", 2, 13)); // NOI18N
        findBSLabel.setText("Find bus stop?");
        findBSLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                findBSLabelMouseClicked(evt);
            }
        });

        fromBox.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                fromBoxItemStateChanged(evt);
            }
        });

        toBox.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                toBoxItemStateChanged(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                    .addComponent(From_label)
                                    .addGap(26, 26, 26))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(to)
                                    .addGap(44, 44, 44)))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(fromBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(toBox, 0, 241, Short.MAX_VALUE)))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(findBSLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 47, Short.MAX_VALUE)
                            .addComponent(searchRoutesButt)))
                    .addComponent(searchroute))
                .addContainerGap(25, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(searchroute)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(From_label)
                    .addComponent(fromBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(to)
                    .addComponent(toBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(searchRoutesButt)
                    .addComponent(findBSLabel))
                .addContainerGap(21, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void findBSLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_findBSLabelMouseClicked
        // TODO add your handling code here:
        this.dispose();
        new findBusStopView(language, color).setVisible(true);
    }//GEN-LAST:event_findBSLabelMouseClicked

    private void searchRoutesButtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchRoutesButtActionPerformed
        //JOptionPane.showMessageDialog(this, from);
        this.dispose();
        new resultView().setVisible(true);
    }//GEN-LAST:event_searchRoutesButtActionPerformed

    private void fromBoxItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_fromBoxItemStateChanged
        from = (String) fromBox.getSelectedItem();
    }//GEN-LAST:event_fromBoxItemStateChanged

    private void toBoxItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_toBoxItemStateChanged
       // to = (String) toBox.getSelectedItem();
    }//GEN-LAST:event_toBoxItemStateChanged

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel From_label;
    private javax.swing.JLabel findBSLabel;
    private javax.swing.JComboBox<String> fromBox;
    private javax.swing.JButton searchRoutesButt;
    private javax.swing.JLabel searchroute;
    private javax.swing.JLabel to;
    private javax.swing.JComboBox<String> toBox;
    // End of variables declaration//GEN-END:variables
}
