/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package transjakarta_;

import javax.swing.JOptionPane;

/**
 *
 * @author Wilson Fransicius
 */
public class settings extends javax.swing.JFrame {

    /**
     * Creates new form settings
     */
    String languages = "english";
    public settings(String language) {
        this.languages = language;
        initComponents();
        this.setLocationRelativeTo(null);
    }
    
    //public String changeLang(){
       //this.setVisible(true);
        //return languages;
    //}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        languages_txt = new javax.swing.JLabel();
        ENG = new javax.swing.JButton();
        ID = new javax.swing.JButton();
        openingView = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        languages_txt.setText("Languages ");

        ENG.setText("English");
        ENG.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ENGActionPerformed(evt);
            }
        });

        ID.setText("Indonesia");
        ID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IDActionPerformed(evt);
            }
        });

        openingView.setText("Main Menu");
        openingView.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                openingViewActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(languages_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(ENG, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(ID))
                    .addComponent(openingView))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(languages_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ENG)
                    .addComponent(ID))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 20, Short.MAX_VALUE)
                .addComponent(openingView)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void IDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IDActionPerformed
        ENG.setEnabled(true);
        languages_txt.setText("Bahasa");
        openingView.setText("Menu Utama");
        ID.setEnabled(false);
        languages = "indo";
        JOptionPane.showMessageDialog(this, "Language Changed");
    }//GEN-LAST:event_IDActionPerformed

    private void ENGActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ENGActionPerformed
        ID.setEnabled(true);
        languages_txt.setText("Languages");
        openingView.setText("Main Menu");
        ENG.setEnabled(false);
        languages= "english";        
        JOptionPane.showMessageDialog(this, "Language Changed");
    }//GEN-LAST:event_ENGActionPerformed

    private void openingViewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_openingViewActionPerformed
        this.dispose();
        new openingView(languages).setVisible(true);
    }//GEN-LAST:event_openingViewActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ENG;
    private javax.swing.JButton ID;
    private javax.swing.JLabel languages_txt;
    private javax.swing.JButton openingView;
    // End of variables declaration//GEN-END:variables
}
