/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;
import Controller.*;
import java.awt.HeadlessException;
import javax.swing.ButtonModel;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JOptionPane;

/**
 *
 * @author Mikha Putri
 */
public class SettingsView extends javax.swing.JFrame {
    
    String language = "eng";
    String color = "pink"; //should be default
    JLabel langLabel;
    JLabel colorLabel;
    JFrame frame;
    ChangeSettings controller;
    String languages, colors;
    
    public SettingsView(String language, String color, JLabel langLabel, JLabel colorLabel) throws HeadlessException {
    this.language = language;
    this.color = color;
    this.langLabel = langLabel;
    this.colorLabel = colorLabel;
    initComponents();
    }
    
    public SettingsView() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        languageGroup = new javax.swing.ButtonGroup();
        colorGroup = new javax.swing.ButtonGroup();
        pinkButton = new javax.swing.JRadioButton();
        grayButton = new javax.swing.JRadioButton();
        okButton = new javax.swing.JButton();
        languageLabel = new javax.swing.JLabel();
        engButton = new javax.swing.JRadioButton();
        indoButton = new javax.swing.JRadioButton();
        colorsLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        colorGroup.add(pinkButton);
        pinkButton.setText("pink");

        colorGroup.add(grayButton);
        grayButton.setText("gray");

        okButton.setText("ok");
        okButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                okButtonActionPerformed(evt);
            }
        });

        languageLabel.setText("language");

        languageGroup.add(engButton);
        engButton.setText("English");
        engButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                engButtonActionPerformed(evt);
            }
        });

        languageGroup.add(indoButton);
        indoButton.setText("Indonesia");

        colorsLabel.setText("color");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(languageLabel)
                    .addComponent(colorsLabel))
                .addGap(51, 51, 51)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(engButton)
                    .addComponent(pinkButton))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(grayButton)
                    .addComponent(indoButton))
                .addContainerGap(59, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(okButton)
                .addGap(37, 37, 37))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(languageLabel)
                    .addComponent(engButton)
                    .addComponent(indoButton))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(colorsLabel)
                    .addComponent(pinkButton)
                    .addComponent(grayButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 37, Short.MAX_VALUE)
                .addComponent(okButton)
                .addGap(21, 21, 21))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void okButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_okButtonActionPerformed
        // TODO add your handling code here:
        ChangeSettings cs = new ChangeSettings();
        if(engButton.isSelected())
        {
            language = "eng";
        }
        else if(indoButton.isSelected())
        {
            language = "indo";
        }
        else{
            if(this.language.equals("eng")){
                languageGroup.setSelected((ButtonModel) engButton, true);
            }
                else{
                    languageGroup.setSelected((ButtonModel) indoButton, true);
                    }
        }
        
        if(pinkButton.isSelected())
            {
                color = "pink";
            }
        else if(grayButton.isSelected())
            {
                color = "gray";
            }
        
        frame = this;
        langLabel = languageLabel;
        colorLabel = colorsLabel;
        cs.change(language, color, languageLabel, colorsLabel, frame);
    }//GEN-LAST:event_okButtonActionPerformed

    private void engButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_engButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_engButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SettingsView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SettingsView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SettingsView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SettingsView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SettingsView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup colorGroup;
    private javax.swing.JLabel colorsLabel;
    private javax.swing.JRadioButton engButton;
    private javax.swing.JRadioButton grayButton;
    private javax.swing.JRadioButton indoButton;
    private javax.swing.ButtonGroup languageGroup;
    private javax.swing.JLabel languageLabel;
    private javax.swing.JButton okButton;
    private javax.swing.JRadioButton pinkButton;
    // End of variables declaration//GEN-END:variables
}
